// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC-e2J1v2uoqYgx_K8wIgek3VwIUO07P8',
    appId: '1:309012364477:web:476939f88a78e9ede1cbd4',
    messagingSenderId: '309012364477',
    projectId: 'housefire-bec45',
    authDomain: 'housefire-bec45.firebaseapp.com',
    databaseURL: 'https://housefire-bec45-default-rtdb.firebaseio.com',
    storageBucket: 'housefire-bec45.appspot.com',
    measurementId: 'G-9MB11REC3E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVYCF5CmYqEE6i16cd3KnwcN3jjD1SdG4',
    appId: '1:309012364477:android:fabc52404ff2a57ae1cbd4',
    messagingSenderId: '309012364477',
    projectId: 'housefire-bec45',
    databaseURL: 'https://housefire-bec45-default-rtdb.firebaseio.com',
    storageBucket: 'housefire-bec45.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeAB55TRv6aZnV64If7FTfRH3MGbUOtTk',
    appId: '1:309012364477:ios:1d2d1da564975d34e1cbd4',
    messagingSenderId: '309012364477',
    projectId: 'housefire-bec45',
    databaseURL: 'https://housefire-bec45-default-rtdb.firebaseio.com',
    storageBucket: 'housefire-bec45.appspot.com',
    iosBundleId: 'com.example.espfire',
  );
}
